# .github/workflows/alerts.yml
name: Daily Telegram Alerts

on:
  schedule:
    # 08:10 Europe/Tallinn is 05:10 UTC
    - cron: '10 5 * * *'

jobs:
  alerts:
    runs-on: ubuntu-latest
    env:
      KAFKA_BOOTSTRAP_SERVERS: ${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
      KAFKA_TOPIC: flights
      FLIGHT_RADAR_TELEGRAM: ${{ secrets.FLIGHT_RADAR_TELEGRAM }}
      ALERT_ALTITUDE_FT: 40000
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Send Telegram Alerts
        run: python scripts/send_alerts.py