name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repo
      - uses: actions/checkout@v3

      # 2. Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install your package & deps
      - name: Install dependencies
        run: |
          cd flight_radar                # move into the folder that contains setup.py
          pip install -r requirements.txt
          pip install -e .               # this makes `import airplane_tracker` work
          pip install pytest

      # 4. Run tests
      - name: Run tests
        run: |
          cd flight_radar
          pytest --maxfail=1 --disable-warnings -q