# .github/workflows/ingest.yml
name: Daily Ingest to Snowflake

on:
  schedule:
    # 08:00 Europe/Tallinn is 05:00 UTC
    - cron: '0 5 * * *'

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      # Define these in GitHub Settings → Secrets → Actions
      KAFKA_BOOTSTRAP_SERVERS: ${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
      KAFKA_TOPIC: flights
      FLIGHT_RADAR_SNOWFLAKE: ${{ secrets.FLIGHT_RADAR_SNOWFLAKE }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Ingest to Snowflake
        run: python scripts/ingest_to_snowflake.py